# Visit the docs for a full walktrough of this file
# https://vippstech.no/docs/default/component/vce-backstage

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: agent-toolkit
  description: this is agent-toolkit
  annotations:
    # backstage.io/techdocs-ref: dir:. # create and place all documentation .MD files under /docs. Uncomment to enable docs
    backstage.io/kubernetes-label-selector: 'app=agent-toolkit' # the same name as in kubernetes
    github.com/project-slug: 'vippsas/agent-toolkit' # to enable CI/CD from GitHub
    # azure.com/tag-selector: app/agent-toolkit # tag key and value to pull your Azure resources in relation to this entity
spec:
  type: service
  lifecycle: experimental
  owner: product-gh-external-developer-docs-admin
